error TS2741: Property 'retire' is missing in type '{ id: number; name: string; }' but required in type '{ readonly id: number; name: string; retire: (date: Date) => void; }'.